package com.nagico.bookstore.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.nagico.bookstore.models.entity.Book;
import com.nagico.bookstore.models.entity.Category;
import com.nagico.bookstore.models.entity.Order;
import com.nagico.bookstore.models.entity.OrderItem;
import com.nagico.bookstore.models.entity.User;

import com.nagico.bookstore.dao.BookDao;
import com.nagico.bookstore.dao.CategoryDao;
import com.nagico.bookstore.dao.OrderDao;
import com.nagico.bookstore.dao.OrderItemDao;
import com.nagico.bookstore.dao.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig bookDaoConfig;
    private final DaoConfig categoryDaoConfig;
    private final DaoConfig orderDaoConfig;
    private final DaoConfig orderItemDaoConfig;
    private final DaoConfig userDaoConfig;

    private final BookDao bookDao;
    private final CategoryDao categoryDao;
    private final OrderDao orderDao;
    private final OrderItemDao orderItemDao;
    private final UserDao userDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        bookDaoConfig = daoConfigMap.get(BookDao.class).clone();
        bookDaoConfig.initIdentityScope(type);

        categoryDaoConfig = daoConfigMap.get(CategoryDao.class).clone();
        categoryDaoConfig.initIdentityScope(type);

        orderDaoConfig = daoConfigMap.get(OrderDao.class).clone();
        orderDaoConfig.initIdentityScope(type);

        orderItemDaoConfig = daoConfigMap.get(OrderItemDao.class).clone();
        orderItemDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        bookDao = new BookDao(bookDaoConfig, this);
        categoryDao = new CategoryDao(categoryDaoConfig, this);
        orderDao = new OrderDao(orderDaoConfig, this);
        orderItemDao = new OrderItemDao(orderItemDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(Book.class, bookDao);
        registerDao(Category.class, categoryDao);
        registerDao(Order.class, orderDao);
        registerDao(OrderItem.class, orderItemDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        bookDaoConfig.clearIdentityScope();
        categoryDaoConfig.clearIdentityScope();
        orderDaoConfig.clearIdentityScope();
        orderItemDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
    }

    public BookDao getBookDao() {
        return bookDao;
    }

    public CategoryDao getCategoryDao() {
        return categoryDao;
    }

    public OrderDao getOrderDao() {
        return orderDao;
    }

    public OrderItemDao getOrderItemDao() {
        return orderItemDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
